export const ADD_TODO="ADD-TODO"
export const TOGGLE_TODO="TOGGLE-TODO"
export const REMOVE_TODO="REMOVE-TODO"
export const MARK_COMPLETED="MARK_COMPLETED"
export const MARK_INCOMPLETE="MARK_INCOMPLETE"
export const FILTER_TODOS="FILTER-TODO"
export const MARK_ALL_COMPLETED="ADD-MARK_ALL_COMPLETED"
export const UPDATE_SEARCH_TERM="UPDATE_SEARCH_TERM"


